package de.scribble.lp.TASTools.misc;

import java.io.File;

import net.minecraft.entity.player.EntityPlayer;

public class MiscSaving {
	private StringBuilder output = new StringBuilder();

	public void saveThings(EntityPlayer player, File file){


		output.append("#This file was generated by TASTools, the author is ScribbleLP. To prevent this file being generated, check the tastools.cfg\n\n");

		output.append("TimeUntilPortal="+player.portalCounter+"\n");
		output.append("END");

		FileStuff.writeThings(output, file, "Saving Misc things");
	}
}
