package de.scribble.lp.TASTools.misc;

import java.io.File;
import java.io.IOException;

import com.google.common.io.Files;

import de.scribble.lp.TASTools.CommonProxy;
import net.minecraft.entity.player.EntityPlayer;

public class MiscSaving {
	private StringBuilder output = new StringBuilder();
	
	public void saveThings(EntityPlayer player, File file){
		

		output.append("#This file was generated by TASTools, the author is ScribbleLP. To prevent this file being generated, check the tastools.cfg\n\n");
		
		output.append("TimeUntilPortal="+player.portalCounter+"\n");
		output.append("END");
		
		try {
			CommonProxy.logger.info("Saving Misc things");
			Files.write(output.toString().getBytes(), file);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
