package de.scribble.lp.TASTools.velocity;

import java.io.File;
import java.io.IOException;

import com.google.common.io.Files;

import de.scribble.lp.TASTools.proxy.CommonProxy;
import net.minecraft.client.Minecraft;
import net.minecraft.entity.player.EntityPlayer;

public class SavingVelocity {
	private StringBuilder output = new StringBuilder();
	private Minecraft mc= Minecraft.getMinecraft();
	
	public void saveVelocity(EntityPlayer player){
		File file= new File(mc.mcDataDir, "saves" + File.separator +mc.getIntegratedServer().getFolderName()+File.separator+"latest_velocity.txt");

		output.append("#This file was generated by TASTools, the author is ScribbleLP. To prevent this file being generated, check the tastools.cfg\n\n");
		
		output.append("XYZ;"+player.motionX+";"+player.motionY+";"+player.motionZ+"\n");
		output.append("END");
		
		try {
			CommonProxy.logger.info("Saving velocity");
			Files.write(output.toString().getBytes(), file);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
